In [71]:
import numpy as np 
import random
import pandas as pd

In [35]:
matrix = np.array([[10,15,20], [25,30,35], [40,45,50 ]])

In [36]:
matrix


array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [37]:
matrix.size

9

In [38]:
matrix.dtype


dtype('int32')

In [39]:
arr = np.random.randint(1,101,10).reshape(2,5)

In [40]:
arr

array([[70,  1, 58, 92, 99],
       [37, 80, 26, 40,  6]])

In [41]:
matrix[0][1]

15

In [42]:
matrix[1][1]

30

In [43]:
matrix

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [44]:
matrix[0][1]


15

In [45]:
matrix[2][2]

50

In [46]:
arr = np.array([10,20,30,40,50])

In [47]:
copy_arr = arr[1:4].copy()

In [48]:
copy_arr

array([20, 30, 40])

In [49]:
copy_arr[0] = 999

In [50]:
copy_arr

array([999,  30,  40])

In [51]:
arr

array([10, 20, 30, 40, 50])

In [52]:
copy_arr 

array([999,  30,  40])

In [53]:
#create an array containing elements from 20 to 40

arr = np.arange(20, 41)


In [54]:
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

In [55]:
# create an array which contain 10 elements and every ekements is 5

arr = np.ones(10)*5

In [56]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [57]:
arr = np.random.randint(1,50,24)

In [58]:
arr

array([30, 26,  7, 26,  2,  4,  1,  5, 11, 44,  6, 10, 28, 49, 32, 47,  9,
       46, 40, 14, 22, 42, 29,  2])

In [59]:
# change 1 d arry into 3d array 
arr =np.random.randint(1,50,24).reshape(3,4,2)

In [60]:
arr

array([[[ 5, 44],
        [ 4, 20],
        [ 6, 38],
        [28, 30]],

       [[10,  1],
        [28,  8],
        [13,  6],
        [33, 35]],

       [[ 3, 11],
        [41,  7],
        [17, 34],
        [22, 35]]])

In [61]:
#create 2d array which contain 25 number 0 to 1
arr = np.random.rand(5,5)


In [62]:
arr

array([[0.60775577, 0.00999396, 0.15283242, 0.74664893, 0.49244912],
       [0.40278748, 0.22875071, 0.62279544, 0.28943136, 0.48715577],
       [0.87832355, 0.07555343, 0.56934602, 0.00194139, 0.48588458],
       [0.34039919, 0.84775426, 0.35544188, 0.58185544, 0.41452424],
       [0.88360716, 0.20685037, 0.74589434, 0.77121038, 0.16990114]])

In [67]:
arr = np.random.seed(123)
arr = np.random.randint(1,50,20)

array([ True, False, False, False, False,  True,  True, False, False,
        True, False,  True,  True, False, False, False,  True,  True,
        True, False])

In [68]:
arr[arr % 2 == 0]

array([46, 18, 20, 34, 48, 10, 48, 26, 20])

In [70]:
arr1 = np.array ([1,2,3])
arr2 = np.array ([4,5,6])
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])